#!/system/bin/sh
# adb: wrapper to run adb from terminal
# osm0sis @ xda-developers

dir="$(cd "$(dirname "$0")"; pwd)";

export HOME=/sdcard;
export TMPDIR=/data/data/com.nightmare/files/usr/tmp;
$dir/adb.bin "$@";

